---
- name: create weechat folder
  file:
    path: ~/.weechat/
    state: directory

- name: copy weechat files
  template:
    src: "{{ item.src }}"
    dest: ~/.weechat/{{ item.path }}
  with_filetree: files/