#!/bin/bash

mkdir -p /tmp/screens
datestr=$(date +%s)
slurp | grim -g - - | convert - -quality 75% /tmp/screens/${datestr}.jpg 

trap "rm /tmp/screens/${datestr}_tmp" EXIT

url=$(curl -s -f --location --request POST $UPLOAD_URL \
--header "Authorization: Bearer $MUPLOAD_TOKEN" \
--form "files[]=@/tmp/screens/${datestr}.jpg")
if [ $? -ne 0 ];
then
	notify-send "curl error"
	exit -1
fi
notify-send "Upload Complete"
echo -n "$url" | wl-copy
