#!/bin/bash

ID=$(swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | . [] | select(.nodes != null) | .nodes | .[] | select(.name != null) | "\(.id?) \(.name?)"' | $FINDUS_MENU -i -l 100 | awk '{print $1}')
swaymsg [con_id="$ID"] focus

